{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"pydantic_core._pydantic_core.ValidationError: 1 validation error for UpdateExerciseResponseSchema\n  Invalid JSON: expected ident at line 1 column 3 [type=json_invalid, input_value='Internal Server Error', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/json_invalid","children":[{"name":"Update exercise","uid":"2efc00bc7b66f214","parentUid":"b6b7ab703898dc765e2a4e9e29f0e1c8","status":"broken","time":{"start":1755631681502,"stop":1755631681511,"duration":9},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":["POSITIVE","exercises","regression"]}],"uid":"b6b7ab703898dc765e2a4e9e29f0e1c8"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}